F.FF
======================================================================
FAIL: test_error_message_if_set_gps_coords_to_null (commandModule.tests.testCases.testReadNullFromPogi.TestCaseReadingNullValuesFromPOGIFiles)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ksisjaya/Desktop/computer_vision_python/modules/commandModule/tests/testCases/testReadNullFromPogi.py", line 29, in test_error_message_if_set_gps_coords_to_null
    self.assertEqual(cm.output, ["ERFROR:root:Value that was passed is null."])
AssertionError: Lists differ: ['ERROR:root:Value that was passed is null.'] != ['ERFROR:root:Value that was passed is null.']

First differing element 0:
'ERROR:root:Value that was passed is null.'
'ERFROR:root:Value that was passed is null.'

- ['ERROR:root:Value that was passed is null.']
+ ['ERFROR:root:Value that was passed is null.']
?     +


======================================================================
FAIL: test_error_message_if_set_gps_coords_to_null (commandModule.tests.testCases.testWriteNullToPigo.TestCaseWritingNullValuesToPIGOFiles)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ksisjaya/Desktop/computer_vision_python/modules/commandModule/tests/testCases/testWriteNullToPigo.py", line 29, in test_error_message_if_set_gps_coords_to_null
    self.assertEqual(cm.output, ["ERFROR:root:Value that was passed is null."])
AssertionError: Lists differ: ['ERROR:root:Value that was passed is null.'] != ['ERFROR:root:Value that was passed is null.']

First differing element 0:
'ERROR:root:Value that was passed is null.'
'ERFROR:root:Value that was passed is null.'

- ['ERROR:root:Value that was passed is null.']
+ ['ERFROR:root:Value that was passed is null.']
?     +


======================================================================
FAIL: test_system_exit_if_set_gps_coords_to_null (commandModule.tests.testCases.testWriteNullToPigo.TestCaseWritingNullValuesToPIGOFiles)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ksisjaya/Desktop/computer_vision_python/modules/commandModule/tests/testCases/testWriteNullToPigo.py", line 20, in test_system_exit_if_set_gps_coords_to_null
    self.assertEqual(cm.exception.code, 2)
AssertionError: 1 != 2

----------------------------------------------------------------------
Ran 4 tests in 0.005s

FAILED (failures=3)
